bazel: update dependencies
Don't update rules_docker because otherwise we get an error like:

    ERROR: /usr/local/google/home/linusa/go/src/sigs.k8s.io/k8s-container-image-promoter/test-e2e/BUILD.bazel:118:1: every rule of type container_push implicitly depends upon the target '@containerregistry//:pusher', but this target could not be found because of: no such package '@containerregistry//': The repository '@containerregistry' could not be resolved
    ERROR: Analysis of target '//test-e2e:push-golden' failed; build aborted: no such package '@containerregistry//': The repository '@containerregistry' could not be resolved
    INFO: Elapsed time: 1.203s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (4 packages loaded, 16 targets configured)
    FAILED: Build did NOT complete successfully (4 packages loaded, 16 targets configured)